<?php

namespace AppBundle\Repository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticleWithComments()
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.comments', 'c')
            ->addSelect('c')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
